### ISSUE TITLE
Gem maintainence

### ISSUE THREAD

**Issue by sivagollapalli** [proton/mongoid_auto_increment#11]
I didn't see any recent activity. I would like to help if you need any?

**Comment by syntruth** [comment]
I second this. I spent an 30 minutes chasing down an issue that you have already fixed, but the Gem was not published. Easy enough to build locally, but I do not want to do that for each of my production servers.

Please officially push the Gem to Rubygems. :)

**Comment by kopchickm** [comment]
I agree!  There are some fixes in master that would be great to get released!  Thanks :)
